[build]
  # Directory containing your serverless functions
  functions = "functions/"
  
  # Directory containing your front-end files (HTML, CSS, JS)
  publish = "public/"

[functions]
  # Ensures the back-end 'node-fetch' dependency is included
  node_bundler = "esbuild"